"""Add seniority_id and company_role_id lookup columns

Revision ID: 85c2e56d7c3c
Revises: e0656b8466ad
Create Date: 2026-03-13 14:38:42.162068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c2e56d7c3c'
down_revision: Union[str, Sequence[str], None] = 'e0656b8466ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experts', sa.Column('seniority_id', sa.Integer(), nullable=True))
    op.add_column('experts', sa.Column('company_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'experts', 'lookup_values', ['seniority_id'], ['id'])
    op.create_foreign_key(None, 'experts', 'lookup_values', ['company_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experts', type_='foreignkey')
    op.drop_constraint(None, 'experts', type_='foreignkey')
    op.drop_column('experts', 'company_role_id')
    op.drop_column('experts', 'seniority_id')
    # ### end Alembic commands ###
