"""Add serial_number column to experts table

Revision ID: e0656b8466ad
Revises: 
Create Date: 2026-03-12 20:57:21.282601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0656b8466ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experts', sa.Column('serial_number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'experts', ['serial_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experts', type_='unique')
    op.drop_column('experts', 'serial_number')
    # ### end Alembic commands ###
